### ISSUE TITLE
R Style Guide?

### ISSUE THREAD

**Issue by DavidOry** [VisionEval/VE-Installer#1]
The R Scripts do not *appear* to adhere to either the [Hadley ](http://adv-r.had.co.nz/Style.html) or [Google ](http://adv-r.had.co.nz/Style.html) style guide. What is the coding standard for R here?

**Comment by jrawbits** [comment]
It adheres to "Jeremy's coding standard", which is admittedly poorly specified and not consistent with the world at large.  We might also want to consider [this standard](https://github.com/VisionEval/VisionEval-Dev/blob/master/api/Coding_Guidelines.md).

**Comment by DavidOry** [comment]
If a goal of the effort is to be developer friendly, then I think we'd want to go with either the Hadley or Google standard. Even though the existing VisionEval standard is well considered, asking a developer to understand and then use a bespoke standard is unfriendly and unnecessary.

**Comment by jrawbits** [comment]
After looking closely at the standards, it's pretty painless to move VE-Installer to the Google standard, which is very close to what I do spontaneously (there's a quibble or two over how to name functions and how to space things in if tests, and of course, the documentation always comes last...). However, that still begs the question of what to do for VisionEval itself; we'll take that on later.

I'll pull the standardized code (with numerous fixes to comments and documentation) into master on VisionEval/VE-Installer once I've verified that I didn't break anything.  In the meantime, if you're curious, you can check out [the "standard-coding" branch on jrawbits/VE-Installer](https://github.com/jrawbits/VE-Installer/tree/standard-coding) (which is **not** a fork of VisionEval/VE-installer, but simply a clone).  Note that using a "non-fork" (but otherwise identical) repository discourages people from basing their own efforts on my side branches (all of which, apart from branches that appear in both VisionEval and jrawbits, are subject to being deleted and rewritten so their history stays useful).

**Comment by jrawbits** [comment]
I particularly like the Google style guideline's "parting words":

> Use common sense and BE CONSISTENT.
> 
> If you are editing code, take a few minutes to look at the code around you and determine its style. If others use spaces around their if clauses, you should, too. If their comments have little boxes of stars around them, make your comments have little boxes of stars around them, too.
> 
> The point of having style guidelines is to have a common vocabulary of coding so people can concentrate on what you are saying, rather than on how you are saying it. We present global style rules here so people know the vocabulary. But local style is also important. If code you add to a file looks drastically different from the existing code around it, the discontinuity will throw readers out of their rhythm when they go to read it. Try to avoid this.

**Comment by dflynn-volpe** [comment]
Agree, comparing 
https://github.com/jrawbits/VE-Installer/blob/standard-coding/build/scripts/build-external-bin.R
to
https://github.com/VisionEval/VE-Installer/blob/master/build/scripts/build-external-bin.R

The standardized version is more human-readable, easier to figure out what is going on, and to figure out which level of logic statement or loop each line is associated with. My only quibble with the Google style is they are more liberal with spaces than I typically am (e.g., say that `if(debug)` should be `if (debug)`).

**Comment by jrawbits** [comment]
The code has been migrated to better reflect the Google coding guidelines.
