### ISSUE TITLE
Check R versions to avoid Entry point error

### ISSUE THREAD

**Issue by dflynn-volpe** [VisionEval/VE-Installer#10]
Relevant issue in r-lang: https://github.com/r-lib/rlang/issues/416

If the user has an old version of R, certain procedures aren't available, such as DATAPTR. We can add a check in the .bat to make sure the installed R matches the downloaded VE version.

**Comment by jrawbits** [comment]
Except that the batch file DOES do a check:  it reaches into the registry, looks for the version of R associated with that particular installer, and requests a download if it doesn't find it.  I think this problem is not likely to afflict brand new users - only ones who have had R and Rstudio lying around for a while.  The question is how to ensure that Rstudio is using the same version of R as VisionEval expects.

I think building a version test into VisionEval.R (and perhaps the .First() function in VisionEval.RData) that runs before any attempt to load the visioneval package might forestall the more dire crash that occurs when the library is loaded.

**Comment by jrawbits** [comment]
Marking this closed as the development branch currently does do some "deep checking" on the R version.
